"""Type stubs for the forgery package."""

from forgery._forgery import Faker as Faker

__all__: list[str]
__version__: str

# Default Faker instance
fake: Faker

# Module-level convenience functions
def seed(value: int) -> None:
    """Seed the default Faker instance for deterministic output.

    Args:
        value: The seed value.
    """
    ...

def name() -> str:
    """Generate a single random full name.

    Returns:
        A full name (first + last).
    """
    ...

def names(n: int) -> list[str]:
    """Generate a batch of random full names.

    Args:
        n: Number of names to generate.

    Returns:
        A list of full names.

    Raises:
        ValueError: If n exceeds the maximum batch size (10 million).
    """
    ...

def first_name() -> str:
    """Generate a single random first name.

    Returns:
        A first name.
    """
    ...

def first_names(n: int) -> list[str]:
    """Generate a batch of random first names.

    Args:
        n: Number of first names to generate.

    Returns:
        A list of first names.

    Raises:
        ValueError: If n exceeds the maximum batch size (10 million).
    """
    ...

def last_name() -> str:
    """Generate a single random last name.

    Returns:
        A last name.
    """
    ...

def last_names(n: int) -> list[str]:
    """Generate a batch of random last names.

    Args:
        n: Number of last names to generate.

    Returns:
        A list of last names.

    Raises:
        ValueError: If n exceeds the maximum batch size (10 million).
    """
    ...

def email() -> str:
    """Generate a single random email address.

    Returns:
        An email address.
    """
    ...

def emails(n: int) -> list[str]:
    """Generate a batch of random email addresses.

    Args:
        n: Number of emails to generate.

    Returns:
        A list of email addresses.

    Raises:
        ValueError: If n exceeds the maximum batch size (10 million).
    """
    ...

def integer(min: int = 0, max: int = 100) -> int:
    """Generate a single random integer within a range.

    Args:
        min: Minimum value (inclusive). Default: 0.
        max: Maximum value (inclusive). Default: 100.

    Returns:
        A random integer.

    Raises:
        ValueError: If min > max.
    """
    ...

def integers(n: int, min: int = 0, max: int = 100) -> list[int]:
    """Generate a batch of random integers within a range.

    Args:
        n: Number of integers to generate.
        min: Minimum value (inclusive). Default: 0.
        max: Maximum value (inclusive). Default: 100.

    Returns:
        A list of random integers.

    Raises:
        ValueError: If min > max or n exceeds the maximum batch size (10 million).
    """
    ...

def uuid() -> str:
    """Generate a single random UUID (version 4).

    Returns:
        A UUID string.
    """
    ...

def uuids(n: int) -> list[str]:
    """Generate a batch of random UUIDs (version 4)."""
    ...

# Float generation
def float_(min: float = 0.0, max: float = 1.0) -> float: ...
def floats(n: int, min: float = 0.0, max: float = 1.0) -> list[float]: ...

# Hash generation
def md5() -> str: ...
def md5s(n: int) -> list[str]: ...
def sha256() -> str: ...
def sha256s(n: int) -> list[str]: ...

# Color generation
def color() -> str: ...
def colors(n: int) -> list[str]: ...
def hex_color() -> str: ...
def hex_colors(n: int) -> list[str]: ...
def rgb_color() -> tuple[int, int, int]: ...
def rgb_colors(n: int) -> list[tuple[int, int, int]]: ...

# DateTime generation
def date(start: str = "2000-01-01", end: str = "2030-12-31") -> str: ...
def dates(n: int, start: str = "2000-01-01", end: str = "2030-12-31") -> list[str]: ...
def date_of_birth(min_age: int = 18, max_age: int = 80) -> str: ...
def dates_of_birth(n: int, min_age: int = 18, max_age: int = 80) -> list[str]: ...
def datetime_(start: str = "2000-01-01", end: str = "2030-12-31") -> str: ...
def datetimes(n: int, start: str = "2000-01-01", end: str = "2030-12-31") -> list[str]: ...

# Text generation
def sentence(word_count: int = 10) -> str: ...
def sentences(n: int, word_count: int = 10) -> list[str]: ...
def paragraph(sentence_count: int = 5) -> str: ...
def paragraphs(n: int, sentence_count: int = 5) -> list[str]: ...
def text(min_chars: int = 50, max_chars: int = 200) -> str: ...
def texts(n: int, min_chars: int = 50, max_chars: int = 200) -> list[str]: ...

# Address generation
def street_address() -> str: ...
def street_addresses(n: int) -> list[str]: ...
def city() -> str: ...
def cities(n: int) -> list[str]: ...
def state() -> str: ...
def states(n: int) -> list[str]: ...
def country() -> str: ...
def countries(n: int) -> list[str]: ...
def zip_code() -> str: ...
def zip_codes(n: int) -> list[str]: ...
def address() -> str: ...
def addresses(n: int) -> list[str]: ...

# Phone generation
def phone_number() -> str: ...
def phone_numbers(n: int) -> list[str]: ...

# Company generation
def company() -> str: ...
def companies(n: int) -> list[str]: ...
def job() -> str: ...
def jobs(n: int) -> list[str]: ...
def catch_phrase() -> str: ...
def catch_phrases(n: int) -> list[str]: ...

# Network generation
def url() -> str: ...
def urls(n: int) -> list[str]: ...
def domain_name() -> str: ...
def domain_names(n: int) -> list[str]: ...
def ipv4() -> str: ...
def ipv4s(n: int) -> list[str]: ...
def ipv6() -> str: ...
def ipv6s(n: int) -> list[str]: ...
def mac_address() -> str: ...
def mac_addresses(n: int) -> list[str]: ...

# Email variants
def safe_email() -> str: ...
def safe_emails(n: int) -> list[str]: ...
def free_email() -> str: ...
def free_emails(n: int) -> list[str]: ...

# Finance generation
def credit_card() -> str: ...
def credit_cards(n: int) -> list[str]: ...
def iban() -> str: ...
def ibans(n: int) -> list[str]: ...
